### ISSUE TITLE
Fix mop-integration build

### ISSUE THREAD

**Issue by hthetiot** [montagejs/mr#113]
Currently mop-integration build fail on travis.
- https://travis-ci.org/montagejs/mr

## MR_VERSION=. MOP_VERSION=0.13 npm run integration
- https://travis-ci.org/montagejs/mr/jobs/218994745
Fail due

```
Testing mop and mr
uncaughtException [ReferenceError: location is not defined]
stack ReferenceError: location is not defined
    at ChildProcess.<anonymous> (/home/travis/build/montagejs/mr/node_modules/mop-integration/lib/exec.js:22:81)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
/home/travis/build/montagejs/mr/node_modules/mop-integration/integration.js:17
    throw error;
    ^
ReferenceError: location is not defined
    at ChildProcess.<anonymous> (/home/travis/build/montagejs/mr/node_modules/mop-integration/lib/exec.js:22:81)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
```

## MR_VERSION=. MOP_VERSION=#master npm run integration
- https://travis-ci.org/montagejs/mr/jobs/218994747
Fail due:

```
uncaughtException [TypeError: optimize(...).fail is not a function]
stack TypeError: optimize(...).fail is not a function
    at test (/home/travis/build/montagejs/mr/node_modules/mop-integration/lib/test.js:17:6)
    at /home/travis/build/montagejs/mr/node_modules/mop-integration/integration.js:83:28
    at _fulfilled (/home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:760:13)
    at /home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:574:44
    at flush (/home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
/home/travis/build/montagejs/mr/node_modules/mop-integration/integration.js:17
    throw error;
    ^
TypeError: optimize(...).fail is not a function
    at test (/home/travis/build/montagejs/mr/node_modules/mop-integration/lib/test.js:17:6)
    at /home/travis/build/montagejs/mr/node_modules/mop-integration/integration.js:83:28
    at _fulfilled (/home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:760:13)
    at /home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:574:44
    at flush (/home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
```

## MR_VERSION=. MOP_VERSION=lastest npm run integration
- https://travis-ci.org/montagejs/mr/jobs/218994746
Fail due:

```
uncaughtException [TypeError: optimize(...).fail is not a function]
stack TypeError: optimize(...).fail is not a function
    at test (/home/travis/build/montagejs/mr/node_modules/mop-integration/lib/test.js:17:6)
    at /home/travis/build/montagejs/mr/node_modules/mop-integration/integration.js:83:28
    at _fulfilled (/home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:760:13)
    at /home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:574:44
    at flush (/home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
/home/travis/build/montagejs/mr/node_modules/mop-integration/integration.js:17
    throw error;
    ^
TypeError: optimize(...).fail is not a function
    at test (/home/travis/build/montagejs/mr/node_modules/mop-integration/lib/test.js:17:6)
    at /home/travis/build/montagejs/mr/node_modules/mop-integration/integration.js:83:28
    at _fulfilled (/home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/home/travis/build/montagejs/mr/node_modules/mop-inRemoving /home/travis/build/montagejs/mr/node_modules/karma-phantomjs-launcher/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1491417218799/phantomjs-2.1.1-linux-x86_64 -> /home/travis/build/montagejs/mr/node_modules/karma-phantomjs-launcher/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/travis/build/montagejs/mr/node_modules/karma-phantomjs-launcher/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated deflate-crc32-stream@0.1.2: module has been merged into crc32-stream
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
tegration/node_modules/q/q.js:760:13)
    at /home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:574:44
    at flush (/home/travis/build/montagejs/mr/node_modules/mop-integration/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
```

**Comment by hthetiot** [comment]
Related to bluebird Promise.fail vs Promise.catch.

Also related to require nodeJS support for 0.13 support.

**Comment by hthetiot** [comment]
related https://github.com/montagejs/mop-integration/pull/5
