### ISSUE TITLE
Unhandled rejection TypeError: Promise.try(...).then is not a function

### ISSUE THREAD

**Issue by rayshan** [montagejs/mr#91]
Error seen with default WebView that comes with the OS.
# 

Android 6.0

```
Unhandled rejection TypeError: Promise.try(...).then is not a function
    at file:///android_asset/www/node_modules/montage/node_modules/mr/require.js:146:14
    at file:///android_asset/www/node_modules/montage/node_modules/mr/require.js:1026:48
    at deepLoad (file:///android_asset/www/node_modules/montage/node_modules/mr/require.js:173:20)
    at load.then.module.error (file:///android_asset/www/node_modules/montage/node_modules/mr/require.js:192:36)
    at r (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:31:5015)
    at r._settlePromiseFromHandler (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:30:10865)
    at r._settlePromise (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:30:11672)
    at r._settlePromise0 (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:30:12371)
    at r._settlePromises (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:30:13742)
    at n._drainQueue (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:29:3008)
    at n._drainQueues (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:29:3069)
    at MutationObserver.drainQueues (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:29:1209)
```

Works after update to web view 4.3:
`"Mozilla/5.0 (Linux; Android 6.0; SAMSUNG-SM-G928A Build/xxx; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/47.0.2526.100 Mobile Safari/537.36"`
# 

Android 5.1.1

```
Unhandled rejection TypeError: Promise.try(...).then is not a function
    at file:///android_asset/www/node_modules/montage/node_modules/mr/require.js:146:14
    at file:///android_asset/www/node_modules/montage/node_modules/mr/require.js:1026:48
    at deepLoad (file:///android_asset/www/node_modules/montage/node_modules/mr/require.js:173:20)
    at load.then.module.error (file:///android_asset/www/node_modules/montage/node_modules/mr/require.js:192:36)
    at r (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:31:5015)
    at r._settlePromiseFromHandler (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:30:10865)
    at r._settlePromise (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:30:11672)
    at r._settlePromise0 (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:30:12371)
    at r._settlePromises (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:30:13742)
    at n._drainQueue (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:29:3008)
    at n._drainQueues (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:29:3069)
    at MutationObserver.drainQueues (file:///android_asset/www/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:29:1209)
```

Broken in:
`"Mozilla/5.0 (Linux; Android 5.1.1; SM-N920T Build/LMY47X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/46.0.2490.76 Mobile Safari/537.36"`

Works after update to web view 4.3:
`"Mozilla/5.0 (Linux; Android 5.1.1; SM-N920T Build/LMY47X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/47.0.2526.100 Mobile Safari/537.36"`

**Comment by hthetiot** [comment]
mr depend bluebird for Promise.
Look like it's not a promise that it's returned in your case.

**Comment by kriskowal** [comment]
Just in case it helps, `Promise.try(f)` is equivalent to `Promise.resolve().then(f)`.

**Comment by hthetiot** [comment]
Nah should be fix now.
Re-open otherwise.

**Comment by Matrosskin** [comment]
What was the problem here?
